name: CI
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install pnpm
        run: npm install --global pnpm
      - name: Install dependencies
        run: yarn
      - name: Generate a template
        run: node index
      - name: Verify that the template is working
        run: node test

      - name: Obtain a GitHub App Installation Access Token
        id: githubAppAuth
        if: github.ref == 'refs/heads/main'
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
      - name: Update template
        if: github.ref == 'refs/heads/main'
        run: ./sync.sh
        env:
          GH_PUSH_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
