name: CI
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install pnpm
        run: npm install --global pnpm
      - name: Install dependencies
        run: yarn
      - name: Generate a template
        run: node index
      - name: Verify that the template is working
        run: node test
      - uses: actions/upload-artifact@v2
        with:
          name: template
          path: template
